### ISSUE TITLE
Netlify Identity Widget missing in Netlify CMS page

### ISSUE THREAD

**Issue by kwickramasekara** [stackbit-themes/starter-nextjs#6]
Per [Netlify documentation](https://www.netlifycms.org/docs/add-to-your-site/#add-the-netlify-identity-widget), their identity widget script needs to be in both site's index page and **CMS index page**. 

You can see the final markup of CMS page does not include this script in the `<head>`:

<img width="990" alt="Screen Shot 2021-03-26 at 12 07 08 PM" src="https://user-images.githubusercontent.com/6528584/112668437-83732a00-8e2c-11eb-8e20-709b0f4f3dd4.png">

**Comment by TomasBankauskas** [comment]
Hi @kwickramasekara, thank you for opening this issue, but this theme was ported to use Next.js and Git and this issue is no longer applicable.
